import { createContext, useContext, useEffect, useMemo, useState, type CSSProperties, type FormEvent, type ReactNode } from "react";
import { useAction, useMutation, useQuery } from "convex/react";
import { Link, NavLink, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import {
  Activity, AlertTriangle, ArrowLeft, ArrowRight, BadgeCheck, Bell, Box, Check, CheckCircle2, ChevronRight,
  Copy, ExternalLink, FileCheck2, Flame, Home, Inbox, Info, LayoutDashboard,
  LoaderCircle, Mail, Menu, PackageCheck, Plus, Radar, ReceiptText, RefreshCw, ScanLine, Search, Send, Shield,
  ShieldCheck, Sparkles, Trash2, UserRound, WandSparkles, X, Zap,
} from "lucide-react";
import { api } from "../convex/_generated/api";
import type { Id } from "../convex/_generated/dataModel";

type HomeContextValue = { sessionToken: string; householdId?: Id<"households">; home: any };
const HomeContext = createContext<HomeContextValue | null>(null);
const ToastContext = createContext<(message: string, tone?: "success" | "info" | "danger") => void>(() => undefined);

const heroSlides = [
  { image: "/images/hero-family-safety.png", eyebrow: "Your home, continuously protected", title: "Know before it becomes dangerous.", copy: "RecallReady connects the things you own to verified safety notices, then tells your family exactly what to do next." },
  { image: "/images/hero-receipt-intelligence.png", eyebrow: "Forward once. Protected for years.", title: "Your receipts become a safety net.", copy: "Send purchase emails to your private inbox. AI identifies each product, while RecallReady quietly watches official sources." },
  { image: "/images/hero-home-inventory.png", eyebrow: "One living record for the whole household", title: "Every product. One protected home.", copy: "Build an inventory without the paperwork. Share it with your household and see every update the moment it happens." },
  { image: "/images/hero-safe-resolution.png", eyebrow: "Evidence, not anxiety", title: "From warning to resolved.", copy: "See the exact model match, the official source, and the remedy. Then track the issue all the way to safe." },
  { image: "/images/hero-black-family-safety.png", eyebrow: "Protection built for every household", title: "Safety that includes the whole family.", copy: "A connected home inventory helps parents, partners, and caregivers act together when a product needs attention." },
];

function getSessionToken(mode: "demo" | "fresh" = "demo") {
  const key = `recallready-session-${mode}`;
  const existing = localStorage.getItem(key);
  if (existing) return existing;
  const token = crypto.randomUUID(); localStorage.setItem(key, token); return token;
}

function App() {
  const [booting, setBooting] = useState(true);
  const [toast, setToast] = useState<{ message: string; tone: string } | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => setBooting(false), 1850); return () => window.clearTimeout(timer); }, []);
  const notify = (message: string, tone: "success" | "info" | "danger" = "success") => { setToast({ message, tone }); window.setTimeout(() => setToast(null), 3600); };
  if (booting) return <BrandLoader />;
  return (
    <ToastContext.Provider value={notify}>
      <Routes>
        <Route path="/" element={<Landing />} />
        <Route path="/app" element={<ProtectedApp />}>
          <Route index element={<Dashboard />} />
          <Route path="inventory" element={<Inventory />} />
          <Route path="inventory/add" element={<AddProduct />} />
          <Route path="inventory/:productId" element={<ProductDetail />} />
          <Route path="import" element={<ImportReceipt />} />
          <Route path="activity" element={<ActivityPage />} />
          <Route path="recalls/:matchId" element={<RecallDetail />} />
          <Route path="settings" element={<Settings />} />
        </Route>
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
      {toast && <div className={`toast ${toast.tone}`}><CheckCircle2 size={19} />{toast.message}</div>}
    </ToastContext.Provider>
  );
}

function BrandLoader() {
  return <div className="brand-loader"><div className="loader-mark"><ShieldCheck/><span className="loader-orbit"/></div><div className="loader-word">Recall<span>Ready</span></div><div className="loader-line"><i/></div><p>Connecting your home to trusted safety sources</p></div>;
}

function Logo({ light = false }: { light?: boolean }) {
  return <span className={`logo ${light ? "logo-light" : ""}`}><span className="logo-icon"><ShieldCheck size={19}/></span>Recall<span>Ready</span></span>;
}

function Landing() {
  const [slide, setSlide] = useState(0); const navigate = useNavigate();
  const openMode = (mode: "demo" | "fresh", path: string) => { localStorage.setItem("recallready-mode", mode); navigate(path); };
  useEffect(() => { const timer = window.setInterval(() => setSlide((value) => (value + 1) % heroSlides.length), 6500); return () => clearInterval(timer); }, []);
  return <main className="landing">
    <header className="landing-nav"><Logo light/><nav><a href="#how">How it works</a><a href="#proof">Why RecallReady</a><button className="nav-cta" onClick={() => openMode("fresh", "/app/settings?mode=fresh")}>Try the live product <ArrowRight size={16}/></button></nav></header>
    <section className="hero">
      {heroSlides.map((item, index) => <div key={item.image} className={`hero-image ${index === slide ? "active" : ""}`} style={{ backgroundImage: `url(${item.image})` }}/>) }
      <div className="hero-shade"/><div className="hero-grain"/>
      <div className="hero-content" key={slide}><p className="eyebrow"><span/><>{heroSlides[slide].eyebrow}</></p><h1>{heroSlides[slide].title}</h1><p className="hero-copy">{heroSlides[slide].copy}</p><div className="hero-actions"><button className="button button-primary" onClick={() => openMode("fresh", "/app/settings?mode=fresh")}>Start my household <ShieldCheck size={18}/></button><button className="button button-ghost" onClick={() => openMode("demo", "/app")}>View guided demo <ChevronRight size={18}/></button></div><p className="hero-note"><Check size={14}/> Use the real empty product flow or explore a guided example</p></div>
      <div className="hero-controls">{heroSlides.map((item, index) => <button key={item.image} className={index === slide ? "active" : ""} onClick={() => setSlide(index)} aria-label={`Show story ${index + 1}`}><span/><em>0{index + 1}</em></button>)}</div>
      <div className="live-proof"><span className="pulse-dot"/><div><strong>Official source monitoring</strong><small>CPSC • FDA • NHTSA</small></div></div>
    </section>
    <section className="trust-strip"><span>POWERED BY</span><strong>Convex</strong><strong>OpenAI</strong><strong>Firecrawl</strong><strong>AgentMail</strong><em>Built for the All Gas Hackathon</em></section>
    <section className="how-section" id="how"><div className="section-heading"><p className="kicker">Protection without paperwork</p><h2>Three quiet steps.<br/>One safer home.</h2><p>RecallReady does the tedious matching work in the background, then shows up only when it matters.</p></div><div className="steps-grid">
      <article><span>01</span><div className="step-icon"><Mail/></div><h3>Forward a receipt</h3><p>Send any order email to your private AgentMail inbox. OpenAI extracts the product and exact model.</p></article>
      <article><span>02</span><div className="step-icon"><Radar/></div><h3>We watch official sources</h3><p>Firecrawl continuously retrieves current notices. Convex matches them to your inventory in real time.</p></article>
      <article><span>03</span><div className="step-icon"><ShieldCheck/></div><h3>Act with confidence</h3><p>Get an evidence backed alert with the affected model, verified source, and precise remedy.</p></article>
    </div></section>
    <section className="proof-section" id="proof"><div className="proof-image"/><div className="proof-copy"><p className="kicker">A better kind of alert</p><h2>The warning finds you.</h2><p>Most recall systems expect people to remember every model they own and repeatedly search government websites. RecallReady reverses that burden.</p><ul><li><BadgeCheck/> Exact model matching, not broad product panic</li><li><FileCheck2/> Every alert links back to its official source</li><li><Zap/> Household updates appear instantly across devices</li></ul><button className="text-button" onClick={() => openMode("fresh", "/app/settings?mode=fresh")}>Try the working product <ArrowRight/></button></div></section>
    <footer><Logo/><p>Product safety that remembers for you.</p><span>Hackathon prototype · 2026</span></footer>
  </main>;
}

function ProtectedApp() {
  const location = useLocation(); const [mode] = useState<"demo" | "fresh">(() => { const requested = new URLSearchParams(location.search).get("mode"); if (requested === "fresh") { localStorage.setItem("recallready-mode", "fresh"); return "fresh"; } return localStorage.getItem("recallready-mode") === "fresh" ? "fresh" : "demo"; }); const [sessionToken] = useState(() => getSessionToken(mode)); const bootstrap = useMutation(api.households.bootstrap); const home = useQuery(api.households.current, { sessionToken }); const [menu, setMenu] = useState(false); const [attempted, setAttempted] = useState(false); const [bootError, setBootError] = useState<string | null>(null); const [connectionSlow, setConnectionSlow] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setConnectionSlow(true), 12_000); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (home === null && !attempted) { setAttempted(true); void bootstrap({ sessionToken, mode }).catch((error: unknown) => setBootError(error instanceof Error ? error.message : "Could not create your household")); } }, [home, attempted, bootstrap, sessionToken, mode]);
  if (bootError || (home === undefined && connectionSlow)) return <ConnectionError message={bootError ?? "RecallReady could not reach its Convex backend. Make sure the local backend is running, then try again."}/>;
  if (!home) return <AppLoader />;
  return <HomeContext.Provider value={{ sessionToken, householdId: home.householdId, home }}><div className="app-shell"><Sidebar open={menu} close={() => setMenu(false)}/><div className="app-main"><AppHeader openMenu={() => setMenu(true)}/><PageTransition><Outlet/></PageTransition></div></div></HomeContext.Provider>;
}

function AppLoader() { return <div className="app-loader"><div className="scan-house"><Home/><i/><b/></div><h2>Preparing your protected home</h2><p>Creating the inventory, connecting sources, and checking for matches…</p><div className="loader-dots"><span/><span/><span/></div></div>; }
function ConnectionError({ message }: { message: string }) { const navigate = useNavigate(); return <div className="app-loader connection-error"><div className="scan-house"><AlertTriangle/><i/><b/></div><h2>We could not open your household</h2><p>{message}</p><div className="connection-actions"><button className="button button-primary" onClick={() => window.location.reload()}><RefreshCw/> Try again</button><button className="button button-ghost" onClick={() => navigate("/")}><ArrowLeft/> Back to home</button></div></div>; }

function PageTransition({ children }: { children: ReactNode }) { const location = useLocation(); return <div key={location.pathname} className="page-enter">{children}</div>; }

function Sidebar({ open, close }: { open: boolean; close: () => void }) {
  const { home } = useHome();
  const links = [{ to: "/app", label: "Overview", icon: LayoutDashboard, end: true }, { to: "/app/inventory", label: "My inventory", icon: Box }, { to: "/app/import", label: "Receipt inbox", icon: Inbox }, { to: "/app/activity", label: "Activity", icon: Activity }];
  const initials = home.memberName.split(/\s+/).map((part: string) => part[0]).join("").slice(0, 2).toUpperCase();
  return <><aside className={`sidebar ${open ? "open" : ""}`}><div className="sidebar-top"><Logo light/><button className="mobile-close" onClick={close} aria-label="Close navigation"><X/></button></div><div className="home-chip"><span>{initials}</span><div><small>Protected household</small><strong>{home.name}</strong></div><ChevronRight/></div><nav>{links.map(({ to, label, icon: Icon, end }) => <NavLink key={to} to={to} end={end} onClick={close} className={({ isActive }) => isActive ? "active" : ""}><Icon size={19}/>{label}</NavLink>)}</nav><div className="sidebar-spacer"/><div className="watch-card"><span><Radar/></span><strong>Monitoring is active</strong><p>Official product safety sources can be checked at any time.</p><div><i/> Live</div></div><NavLink className="settings-link" to="/app/settings" onClick={close}><UserRound/> Household settings</NavLink></aside>{open && <button className="sidebar-scrim" onClick={close} aria-label="Close navigation"/>}</>;
}

function AppHeader({ openMenu }: { openMenu: () => void }) { const location = useLocation(); const navigate = useNavigate(); const { home } = useHome(); const titles: Record<string,string> = { "/app": "Overview", "/app/inventory": "My inventory", "/app/inventory/add": "Add a product", "/app/import": "Receipt inbox", "/app/activity": "Activity", "/app/settings": "Household settings" }; const title = location.pathname.startsWith("/app/recalls") ? "Recall details" : location.pathname.match(/^\/app\/inventory\//) ? "Product record" : titles[location.pathname] ?? "RecallReady"; const initials = home.memberName.split(/\s+/).map((part: string) => part[0]).join("").slice(0, 2).toUpperCase(); return <header className="app-header"><button className="menu-button" onClick={openMenu} aria-label="Open navigation"><Menu/></button><div><p>{home.name}</p><h1>{title}</h1></div><div className="header-actions"><button aria-label="Search inventory" onClick={() => navigate("/app/inventory")}><Search/></button><button className="notification" aria-label="View activity" onClick={() => navigate("/app/activity")}><Bell/><i/></button><span className="avatar">{initials}</span></div></header>; }

function useHome() { const value = useContext(HomeContext); if (!value) throw new Error("Home context unavailable"); return value; }
function useNotify() { return useContext(ToastContext); }

function Dashboard() {
  const { sessionToken, householdId, home } = useHome(); const overview = useQuery(api.dashboard.overview, householdId ? { sessionToken, householdId } : "skip"); const scan = useAction(api.integrations.scanLatest); const notify = useNotify(); const [scanning, setScanning] = useState(false); const navigate = useNavigate();
  if (!overview) return <ContentSkeleton/>;
  const openMatch = overview.matches.find((item: any) => item.status !== "resolved");
  const roomCount = new Set(overview.products.map((product: any) => product.room)).size;
  const lastChecked = overview.lastRun?.completedAt ?? overview.lastRun?.startedAt;
  const today = new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date());
  const runScan = async () => { setScanning(true); try { const result = await scan({ sessionToken }); notify(result.matchesFound ? `${result.message} ${result.matchesFound} new match found.` : result.message); } catch (error) { notify(error instanceof Error ? error.message : "The source scan could not complete.", "danger"); } finally { setScanning(false); } };
  return <div className="page dashboard-page"><section className="welcome-row"><div><p className="kicker">{today}</p><h2>Good evening, {home.memberName.split(" ")[0]}.</h2><p>{overview.stats.openAlerts ? `Your home has ${overview.stats.openAlerts} safety ${overview.stats.openAlerts === 1 ? "item" : "items"} that need attention.` : "Everything currently monitored is clear."}</p></div><button className="button button-dark" onClick={runScan} disabled={scanning}>{scanning ? <LoaderCircle className="spin"/> : <RefreshCw/>}{scanning ? "Checking sources…" : "Check sources now"}</button></section>
    {scanning && <ScanOverlay/>}
    <section className="status-grid"><div className="score-card"><div className="score-ring" style={{ "--score": `${overview.stats.protectionScore * 3.6}deg` } as CSSProperties}><span>{overview.stats.protectionScore}</span><small>/100</small></div><div><p>Home protection score</p><h3>{overview.stats.openAlerts ? "Action recommended" : "Strong coverage"}</h3><span><i/> Live monitoring active</span></div></div><StatCard icon={<PackageCheck/>} value={overview.stats.protectedProducts} label="Products protected" meta={`Across ${roomCount} ${roomCount === 1 ? "room" : "rooms"}`}/><StatCard icon={<Radar/>} value="1" label="Official source" meta={lastChecked ? `Last checked ${relativeTime(lastChecked)} ago` : "Ready to check"}/><StatCard danger icon={<AlertTriangle/>} value={overview.stats.openAlerts} label="Action needed" meta={overview.stats.openAlerts ? "Exact model match" : "No open matches"}/></section>
    {openMatch && <section className="alert-feature"><div className="alert-photo"/><div className="alert-body"><div className="alert-meta"><span><Flame/> Action needed</span><em>{Math.round(openMatch.confidence * 100)}% exact match</em></div><h2>{openMatch.product.name} has been recalled.</h2><p>{openMatch.recall.hazard}</p><div className="model-row"><span>Your model <strong>{openMatch.product.modelNumber}</strong></span><span>Source <strong>{openMatch.recall.agency}</strong></span><span>Found <strong>{relativeTime(openMatch.createdAt)} ago</strong></span></div><button className="button button-alert" onClick={() => navigate(`/app/recalls/${openMatch._id}`)}>Review safety action <ArrowRight/></button></div></section>}
    <section className="dashboard-lower"><div className="panel"><div className="panel-heading"><div><p className="kicker">Household inventory</p><h3>Recently protected</h3></div><Link to="/app/inventory">View all <ArrowRight/></Link></div><div className="product-list">{overview.products.slice(0,4).map((product: any) => <ProductRow key={product._id} product={product}/>)}</div></div><div className="panel"><div className="panel-heading"><div><p className="kicker">Live from Convex</p><h3>Protection activity</h3></div><span className="realtime-badge"><i/> Real time</span></div><div className="timeline">{overview.events.slice(0,5).map((event: any) => <TimelineItem key={event._id} event={event}/>)}</div><Link className="panel-link" to="/app/activity">See complete activity <ArrowRight/></Link></div></section>
    <section className="inbox-banner"><div className="inbox-icon"><Mail/></div><div><p className="kicker">The easiest way to add products</p><h3>Forward any receipt to <button onClick={() => { void navigator.clipboard.writeText(home.inboxEmail); notify("Private inbox copied."); }}>{home.inboxEmail}<Copy/></button></h3><p>AgentMail receives it. OpenAI finds the product and model. Convex starts watching it.</p></div><Link className="button button-cream" to="/app/import">Try a receipt <ArrowRight/></Link></section>
  </div>;
}

function StatCard({ icon, value, label, meta, danger = false }: { icon: ReactNode; value: string | number; label: string; meta: string; danger?: boolean }) { return <div className={`stat-card ${danger ? "danger" : ""}`}><span>{icon}</span><strong>{value}</strong><p>{label}</p><small>{meta}</small></div>; }
function ProductRow({ product }: { product: any }) { const icons: Record<string,string> = { Kitchen: "🍳", Children: "◌", Appliances: "✦", Electronics: "⌁" }; return <div className="product-row"><span className="product-thumb">{icons[product.category] ?? "□"}</span><div><strong>{product.name}</strong><small>{product.brand} · {product.modelNumber}</small></div><em>{product.room}</em><span className={`status ${product.status}`}><i/>{product.status === "clear" ? "Clear" : product.status === "review" ? "Reviewing" : "Recalled"}</span></div>; }
function TimelineItem({ event }: { event: any }) { const icon = event.type === "match_found" ? <AlertTriangle/> : event.type === "scan_completed" ? <Radar/> : event.type === "match_resolved" ? <Check/> : event.type === "alert_sent" ? <Send/> : <ReceiptText/>; return <div className="timeline-item"><span>{icon}</span><div><strong>{event.title}</strong><p>{event.detail}</p></div><time>{relativeTime(event.createdAt)}</time></div>; }
function relativeTime(time: number) { const minutes = Math.floor((Date.now() - time) / 60_000); if (minutes < 60) return `${Math.max(1, minutes)}m`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h`; return `${Math.floor(hours / 24)}d`; }
function ScanOverlay() { return <div className="scan-overlay"><div className="scan-visual"><Radar/><span/><i/></div><h3>Checking official safety sources</h3><p>Firecrawl is retrieving the latest notices and matching them against your Convex inventory.</p><div className="scan-stages"><span className="done"><Check/> Connect</span><i/><span className="active"><LoaderCircle/> Retrieve</span><i/><span>Match</span></div></div>; }

function Inventory() {
  const { sessionToken, householdId } = useHome(); const products = useQuery(api.products.list, { sessionToken, householdId: householdId! }); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All");
  const shown = useMemo(() => (products ?? []).filter((p: any) => (filter === "All" || p.status === filter.toLowerCase()) && `${p.name} ${p.brand} ${p.modelNumber}`.toLowerCase().includes(query.toLowerCase())), [products, filter, query]);
  return <div className="page"><PageHero image="/images/hero-home-inventory.png" eyebrow="A living record of what you own" title="Your protected inventory" copy="Every model stays connected to new safety information for as long as it lives in your home." action={<Link className="button button-primary" to="/app/inventory/add"><Plus/> Add a product</Link>}/><div className="toolbar"><label><Search/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search product, brand, or model…"/></label><div className="filters">{["All","Clear","Review","Recalled"].map((value) => <button className={filter === value ? "active" : ""} onClick={() => setFilter(value)} key={value}>{value}</button>)}</div></div>{shown.length === 0 ? <EmptyState icon={<Box/>} title="No products found" text={products?.length ? "Try a different search or status filter." : "Add a product or process a receipt to start monitoring your home."}/> : <div className="inventory-grid">{shown.map((product: any, index: number) => <article className="inventory-card" key={product._id} style={{ animationDelay: `${index * 60}ms` }}><div className={`inventory-visual visual-${index % 4}`}><span>{product.category === "Kitchen" ? "🍳" : product.category === "Children" ? "◌" : product.category === "Electronics" ? "⌁" : "✦"}</span><div className={`status ${product.status}`}><i/>{product.status}</div></div><div className="inventory-info"><p>{product.category} · {product.room}</p><h3>{product.name}</h3><span>{product.brand}</span><dl><div><dt>Model</dt><dd>{product.modelNumber}</dd></div><div><dt>Added via</dt><dd>{product.source}</dd></div></dl><Link to={`/app/inventory/${product._id}`}>View product record <ArrowRight/></Link></div></article>)}</div>}</div>;
}

function AddProduct() {
  const { sessionToken, householdId } = useHome(); const add = useMutation(api.products.add); const notify = useNotify(); const navigate = useNavigate(); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await add({ sessionToken, householdId: householdId!, name: String(data.get("name")), brand: String(data.get("brand")), modelNumber: String(data.get("model")), serialNumber: String(data.get("serial")) || undefined, category: String(data.get("category")), room: String(data.get("room")), retailer: String(data.get("retailer")) || undefined, purchaseDate: String(data.get("date")) || undefined }); notify("Product added and monitoring started."); navigate("/app/inventory"); } catch (error) { notify(error instanceof Error ? error.message : "Product could not be added.", "danger"); setSaving(false); } };
  return <div className="page form-page"><Link className="back-link" to="/app/inventory"><ArrowLeft/> Back to inventory</Link><div className="form-layout"><section><p className="kicker">Manual product record</p><h2>Add something you own.</h2><p>Model numbers make safety matching precise. You can usually find yours on the product label, packaging, or order confirmation.</p><div className="label-guide"><ScanLine/><div><strong>Where is the model number?</strong><p>Look for “Model”, “M/N”, or “Type” near a barcode or compliance label.</p></div></div></section><form className="premium-form" onSubmit={submit}><div className="form-progress"><span className="active">1</span><i/><span>2</span><p>Product details</p></div><div className="field-row"><label>Product name<input required name="name" placeholder="e.g. Air fryer"/></label><label>Brand<input required name="brand" placeholder="e.g. CookWell"/></label></div><label>Model number <span>Most important</span><input required name="model" placeholder="e.g. CW AF900"/></label><label>Serial number <small>Optional</small><input name="serial" placeholder="e.g. SN 2849 7712"/></label><div className="field-row"><label>Category<select name="category"><option>Kitchen</option><option>Electronics</option><option>Children</option><option>Appliances</option><option>Automotive</option></select></label><label>Room<select name="room"><option>Kitchen</option><option>Living room</option><option>Nursery</option><option>Home office</option><option>Utility</option></select></label></div><div className="field-row"><label>Retailer <small>Optional</small><input name="retailer" placeholder="Where you bought it"/></label><label>Purchase date <small>Optional</small><input type="date" name="date"/></label></div><div className="form-actions"><Link to="/app/inventory" className="button button-subtle">Cancel</Link><button className="button button-primary" disabled={saving}>{saving ? <LoaderCircle className="spin"/> : <ShieldCheck/>}{saving ? "Starting protection…" : "Add & start monitoring"}</button></div></form></div></div>;
}

function ProductDetail() {
  const { productId } = useParams(); const { sessionToken } = useHome(); const product = useQuery(api.products.get, productId ? { sessionToken, productId: productId as Id<"products"> } : "skip"); const update = useMutation(api.products.update); const remove = useMutation(api.products.remove); const notify = useNotify(); const navigate = useNavigate(); const [saving, setSaving] = useState(false); const [removing, setRemoving] = useState(false);
  if (product === undefined) return <ContentSkeleton/>;
  if (product === null) return <div className="page"><EmptyState icon={<Box/>} title="Product not found" text="This record may have been removed from the household."/><Link className="button button-dark" to="/app/inventory">Back to inventory</Link></div>;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await update({ sessionToken, productId: product._id, name: String(data.get("name")), brand: String(data.get("brand")), modelNumber: String(data.get("model")), serialNumber: String(data.get("serial")) || undefined, category: String(data.get("category")), room: String(data.get("room")), retailer: String(data.get("retailer")) || undefined, purchaseDate: String(data.get("date")) || undefined }); notify("Product record updated."); } catch (error) { notify(error instanceof Error ? error.message : "Product could not be updated.", "danger"); } finally { setSaving(false); } };
  const deleteProduct = async () => { if (!window.confirm(`Remove ${product.name} from this household?`)) return; setRemoving(true); try { await remove({ sessionToken, productId: product._id }); notify("Product removed from monitoring."); navigate("/app/inventory"); } catch (error) { notify(error instanceof Error ? error.message : "Product could not be removed.", "danger"); setRemoving(false); } };
  return <div className="page form-page"><Link className="back-link" to="/app/inventory"><ArrowLeft/> Back to inventory</Link><div className="form-layout"><section><p className="kicker">Protected product record</p><h2>{product.name}</h2><p>Keep the identifying details accurate so exact-model recall matching remains reliable.</p><div className={`record-status status ${product.status}`}><i/>{product.status}</div><p className="record-meta">Added {new Date(product.addedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })} via {product.source}.</p><button className="button danger-outline" type="button" onClick={deleteProduct} disabled={removing}>{removing ? <LoaderCircle className="spin"/> : <Trash2/>}{removing ? "Removing…" : "Remove product"}</button></section><form className="premium-form" onSubmit={submit}><div className="field-row"><label>Product name<input required name="name" defaultValue={product.name}/></label><label>Brand<input required name="brand" defaultValue={product.brand}/></label></div><label>Model number <span>Most important</span><input required name="model" defaultValue={product.modelNumber}/></label><label>Serial number <small>Optional</small><input name="serial" defaultValue={product.serialNumber ?? ""}/></label><div className="field-row"><label>Category<input required name="category" defaultValue={product.category}/></label><label>Room<input required name="room" defaultValue={product.room}/></label></div><div className="field-row"><label>Retailer <small>Optional</small><input name="retailer" defaultValue={product.retailer ?? ""}/></label><label>Purchase date <small>Optional</small><input type="date" name="date" defaultValue={product.purchaseDate ?? ""}/></label></div><div className="form-actions"><Link to="/app/inventory" className="button button-subtle">Cancel</Link><button className="button button-primary" disabled={saving}>{saving ? <LoaderCircle className="spin"/> : <ShieldCheck/>}{saving ? "Saving…" : "Save product"}</button></div></form></div></div>;
}

function ImportReceipt() {
  const { sessionToken, home } = useHome(); const process = useAction(api.integrations.processReceipt); const notify = useNotify(); const navigate = useNavigate(); const [text, setText] = useState("Order confirmed at Everyday Home\n1 × Harbor & Finch Smart Steam Kettle\nModel: HF K220\nThank you for your purchase."); const [processing, setProcessing] = useState(false); const [step, setStep] = useState(0);
  const run = async () => { setProcessing(true); setStep(1); await new Promise((resolve) => setTimeout(resolve, 450)); setStep(2); try { const result = await process({ sessionToken, receiptText: text }); setStep(3); notify(result.matchesFound ? `${result.productName} is protected and matched a safety notice.` : `${result.productName} is now protected.`); setTimeout(() => navigate("/app/inventory"), 1200); } catch (error) { setProcessing(false); setStep(0); notify(error instanceof Error ? error.message : "We could not process that receipt.", "danger"); } };
  return <div className="page"><PageHero image="/images/hero-receipt-intelligence.png" eyebrow="Your private AgentMail inbox" title="Forward it. Forget it." copy="Purchase emails become clean product records, automatically watched against official safety notices."/><div className="import-layout"><section className="inbox-address-card"><span><Mail/></span><p>Forward receipts to</p><button onClick={() => { void navigator.clipboard.writeText(home.inboxEmail); notify("Inbox address copied."); }}>{home.inboxEmail}<Copy/></button><small>Private to {home.name}</small><div className="email-flow"><i><Mail/></i><b/><i><WandSparkles/></i><b/><i><ShieldCheck/></i></div><ul><li><Check/> Order confirmations</li><li><Check/> Digital receipts</li><li><Check/> Product registration emails</li></ul></section><section className="receipt-lab"><div className="lab-heading"><div><p className="kicker">Interactive demo</p><h3>See the inbox intelligence work</h3></div><span><Sparkles/> OpenAI extraction</span></div><label>Paste a receipt or order email<textarea value={text} onChange={(event) => setText(event.target.value)} disabled={processing}/></label>{processing ? <div className="processing-flow"><ProcessStep active={step >= 1} done={step > 1} icon={<Mail/>} text="Receipt received by AgentMail"/><ProcessStep active={step >= 2} done={step > 2} icon={<WandSparkles/>} text="OpenAI extracting product details"/><ProcessStep active={step >= 3} done={false} icon={<ShieldCheck/>} text="Convex starting live protection"/></div> : <button className="button button-dark full" onClick={run} disabled={!text.trim()}><WandSparkles/> Process this receipt</button>}</section></div></div>;
}
function ProcessStep({ active, done, icon, text }: { active: boolean; done: boolean; icon: ReactNode; text: string }) { return <div className={`${active ? "active" : ""} ${done ? "done" : ""}`}><span>{done ? <Check/> : icon}</span><p>{text}</p>{active && !done && <LoaderCircle className="spin"/>}</div>; }

function ActivityPage() { const { sessionToken, householdId } = useHome(); const events = useQuery(api.dashboard.activity, { sessionToken, householdId: householdId! }); return <div className="page"><PageHero image="/images/hero-family-safety.png" eyebrow="Every action, clearly recorded" title="Protection activity" copy="A transparent, real time history of what entered your home, what we checked, and what changed."/><div className="activity-layout"><div className="activity-summary"><span><Activity/></span><div><strong>{events?.length ?? 0}</strong><p>Recorded events</p></div><i/><div><strong>4</strong><p>Integration paths</p></div><i/><div><strong>Live</strong><p>Convex sync</p></div></div><section className="activity-feed">{events?.length ? events.map((event: any, index: number) => <div className="activity-event" key={event._id}><div className="event-date"><strong>{index === 0 ? "Now" : new Date(event.createdAt).toLocaleDateString("en-US", { month: "short", day: "numeric" })}</strong><small>{new Date(event.createdAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}</small></div><span className={`event-node type-${event.type}`}><Activity/></span><div><h3>{event.title}</h3><p>{event.detail}</p><em>{event.type.replaceAll("_", " ")}</em></div></div>) : <EmptyState icon={<Activity/>} title="No activity yet" text="Household changes and source checks will appear here."/>}</section></div></div>; }

function RecallDetail() {
  const { matchId } = useParams(); const { sessionToken, home } = useHome(); const details = useQuery(api.recalls.getMatch, matchId ? { sessionToken, matchId: matchId as Id<"matches"> } : "skip"); const setStatus = useMutation(api.recalls.setStatus); const send = useAction(api.integrations.sendSafetyDigest); const notify = useNotify(); const navigate = useNavigate(); const [resolving, setResolving] = useState(false); const [sent, setSent] = useState(false);
  if (details === undefined) return <ContentSkeleton/>;
  if (details === null) return <div className="page"><EmptyState icon={<AlertTriangle/>} title="Safety match not found" text="This alert may have been removed or belongs to another household."/><Link className="button button-dark" to="/app">Back to overview</Link></div>;
  const { match, product, recall } = details;
  const resolve = async () => { setResolving(true); try { await setStatus({ sessionToken, matchId: match._id, status: "resolved" }); notify("Safety issue resolved. Your protection score is updating."); setTimeout(() => navigate("/app"), 800); } catch (error) { notify(error instanceof Error ? error.message : "The safety action could not be updated.", "danger"); setResolving(false); } };
  const sendAlert = async () => { try { const result = await send({ sessionToken, matchId: match._id }); setSent(true); notify(result.message, "info"); } catch (error) { notify(error instanceof Error ? error.message : "The alert could not be sent.", "danger"); if (!home.memberEmail) setTimeout(() => navigate("/app/settings"), 900); } };
  return <div className="page recall-page"><Link className="back-link light" to="/app"><ArrowLeft/> Back to overview</Link><div className="recall-hero" style={{ backgroundImage: "url(/images/hero-safe-resolution.png)" }}><div/><div className="recall-hero-content"><span><AlertTriangle/> Verified safety match</span><p>{recall.agency} · Published {new Date(recall.publishedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p><h2>{product.name} needs your attention.</h2><p>{recall.hazard}</p></div></div><div className="recall-content"><main><section className="match-proof"><div className="match-score"><strong>{Math.round(match.confidence * 100)}%</strong><span>match confidence</span></div><div><p className="kicker">Why this matched</p><h3>Your exact model is listed.</h3><p>{match.explanation}</p><div className="compare-row"><span><small>Your product</small><strong>{product.brand} · {product.modelNumber}</strong></span><ArrowRight/><span><small>Official notice</small><strong>{recall.brands[0]} · {recall.modelNumbers[0]}</strong></span></div></div></section><section className="remedy-card"><span>01</span><div><p className="kicker">Recommended action</p><h3>Follow the official remedy.</h3><p>{recall.remedy}</p><a href={recall.sourceUrl} target="_blank" rel="noreferrer">Open official notice <ExternalLink/></a></div></section><section className="evidence-card"><div className="panel-heading"><div><p className="kicker">Evidence trail</p><h3>Built to be trusted</h3></div><BadgeCheck/></div><dl><div><dt>Authority</dt><dd>{recall.agency}</dd></div><div><dt>Source</dt><dd>{recall.sourceLabel}</dd></div><div><dt>Source status</dt><dd><i/> {recall.isDemo ? "Demonstration" : "Official"}</dd></div><div><dt>Last verified</dt><dd>{relativeTime(recall.crawledAt)} ago</dd></div></dl>{recall.isDemo && <p><Info/> This is a clearly labelled demonstration fixture. Live retrieval activates when Firecrawl is configured.</p>}</section></main><aside className="action-panel"><span className="action-icon"><Shield/></span><h3>Complete the safety action</h3><p>Use the manufacturer’s remedy, then mark this resolved to update your household record.</p><ol><li className="done"><Check/> Stop using product</li><li><span>2</span> Contact manufacturer</li><li><span>3</span> Complete remedy</li></ol><button className="button button-alert full" onClick={resolve} disabled={resolving || match.status === "resolved"}>{resolving ? <LoaderCircle className="spin"/> : <CheckCircle2/>}{match.status === "resolved" ? "Resolved" : resolving ? "Updating household…" : "Mark as resolved"}</button><button className="button button-subtle full" onClick={sendAlert} disabled={sent}><Mail/>{sent ? "Alert prepared" : "Email this to me"}</button><small>Actions sync instantly to every household member.</small></aside></div></div>;
}

function Settings() { const { sessionToken, home } = useHome(); const updateProfile = useMutation(api.households.updateProfile); const loadStatus = useAction(api.integrations.integrationStatus); const notify = useNotify(); const [saving, setSaving] = useState(false); const [status, setStatus] = useState<{ openAI: boolean; firecrawl: boolean; agentMail: boolean } | null>(null); useEffect(() => { void loadStatus({ sessionToken }).then(setStatus).catch(() => setStatus({ openAI: false, firecrawl: false, agentMail: false })); }, [loadStatus, sessionToken]); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); const data = new FormData(event.currentTarget); try { await updateProfile({ sessionToken, name: String(data.get("name")), memberName: String(data.get("memberName")), memberEmail: String(data.get("email")) || undefined }); notify("Household settings saved."); } catch (error) { notify(error instanceof Error ? error.message : "Settings could not be saved.", "danger"); } finally { setSaving(false); } }; return <div className="page"><PageHero image="/images/hero-family-safety.png" eyebrow="Shared protection" title="Household settings" copy="Manage the people, inbox, and services that keep your home covered."/><div className="settings-grid"><form className="panel settings-panel" onSubmit={submit}><h3>Household profile</h3><label>Household name<input required name="name" defaultValue={home.name}/></label><label>Your name<input required name="memberName" defaultValue={home.memberName}/></label><label>Alert email<input name="email" type="email" defaultValue={home.memberEmail ?? ""} placeholder="you@example.com"/></label><label>Private inbox<input value={home.inboxEmail} readOnly/></label><button className="button button-dark" disabled={saving}>{saving ? <LoaderCircle className="spin"/> : <ShieldCheck/>}{saving ? "Saving…" : "Save changes"}</button></form><section className="panel integrations-panel"><h3>Connected intelligence</h3><Integration name="Convex" text="Database, functions and realtime sync" live/><Integration name="OpenAI" text="Receipt understanding" live={status?.openAI}/><Integration name="Firecrawl" text="Official source retrieval" live={status?.firecrawl}/><Integration name="AgentMail" text="Inbound receipts and safety alerts" live={status?.agentMail}/></section></div></div>; }
function Integration({ name, text, live = false }: { name: string; text: string; live?: boolean }) { return <div><span>{name[0]}</span><p><strong>{name}</strong><small>{text}</small></p><em className={live ? "connected" : "demo"}>{live ? "Connected" : "Demo ready"}</em></div>; }

function PageHero({ image, eyebrow, title, copy, action }: { image: string; eyebrow: string; title: string; copy: string; action?: ReactNode }) { return <section className="page-hero" style={{ backgroundImage: `url(${image})` }}><div className="page-hero-shade"/><div className="page-hero-content"><p className="eyebrow"><span/>{eyebrow}</p><h2>{title}</h2><p>{copy}</p>{action}</div></section>; }
function ContentSkeleton() { return <div className="content-skeleton"><div/><div className="skeleton-grid"><span/><span/><span/></div><div/></div>; }
function EmptyState({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="empty-state"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>; }

export default App;
